### ISSUE TITLE
Destructive behavior of “add as destination”

### ISSUE THREAD

**Issue by shinkolobwe** [GIScience/ors-map-client#102]
Hello

I may also add that the old right-mouse-click-context-menu item “add as via point” was much more intuitive for me. A “via point” is for me a clearly defined phrase. The context-menu items in the new layout show behavior for me that is quite unexpected. 

It can even happen that a constructed route is completely lost if a wrong item is selected at the end of a route building process.

The “direct to here” function would be expected to just add a final destination point. But what actually happens is that all “via points” are removed - beyond return, it seems. Even if this behavior is known to the user, it may happen inadvertedly and cause a route to be lost! Not to be desired.
Best wishes
Christian

**Comment by amoncaldas** [comment]
Hello again @shinkolobwe 

I see your point, but `add stop here` seems to be also a way to communicate it. I think both are understood by users.

The route displayed on the app is synchronized with the URL, so that if the URL is shared/copied, it will render the exact route. 
The flow is: 
- detect changes made by the user via inputs or map interactions
- create a new URL based on the data/parameters, 
- redirect the app to the new URL 
- calculate the route based on the URL
- Show the route. 

If it fails on the last step (calculate) then I understand that it would not be a good strategy to return to a old URL.

`Direct to here` means indeed `direct`, without stop. There are already the `add stop here` and `Append as destination` options.
Thanks for your feedback. we really appreciate it.
Best wishes.
Amon

**Comment by shinkolobwe** [comment]
Ok good evening, the terminology is so confusing and actually unclear because the term "direct to" is a verb. 

see here: https://dict.leo.org/german-english/direct%20to

So the term "direct to" will be commonly understood as a command to add the point as the final destination. "direct me to the beach", for example.

**Comment by amoncaldas** [comment]
Hi. Good morning.
Actually `direct` has several meanings. It is a `verb`, and `adjective` and an `adverb`. According as the Merriam Webster dictionary (a reference dictionary for US English) https://www.merriam-webster.com/dictionary/direct

As an adverb it means: `from point to point without deviation : by the shortest way`. They also provide an example of usage as an adverb: "flew direct to Miami". This is exactly what the term means in the app context.

**Comment by amoncaldas** [comment]
Hey @shinkolobwe. The route "destructive" behavior was fixed. I managed to find a better way to deal with it in the code.
Thanks for reporting.
