### ISSUE TITLE
the routing doesn't respect no_u_turn restriction

### ISSUE THREAD

**Issue by zorglubu** [GIScience/ors-map-client#115]
Hello,
First of all, thanks a lot for your wonderful website :-)

On the following routing, there is a restriction relation since it's not allowed to u_turn. This relation seems to be ignored.
The relation is https://www.openstreetmap.org/relation/9394089

the routing exemple : https://maps.openrouteservice.org/#/directions/38%20Avenue%20Du%20G%C3%A9n%C3%A9ral%20Leclerc,L'Ha%C3%BF-les-Roses,France/14%20Rue%20De%20l'Orme%20Sec,L'Ha%C3%BF-les-Roses,France/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,38,0,232,6,102,63,98,4,96,5,128,14,90,104,19,129,186,41,160,26,91,8,29,139,171,240,1,159,141,124,244,105,112,10,192,27,136,153,6,196,107,247,17,95,57,9,84,228,113,173,215,169,10,0,217,139,240,106,207,85,16,108,64,64,0,234,158,4,68,216,114,130,189,2,0,51,120,0,109,210,225,11,26,60,0,27,146,0,57,128,45,24,50,52,57,136,11,186,27,186,52,58,34,24,15,158,38,0,5,140,6,38,42,12,64,23,148,0,45,174,43,0,47,153,80,0

**Comment by amoncaldas** [comment]
Hey @zorglubu 
Thanks for reaching us. 
This possible issue seems to be on the back-end  and not on the client, since the client does not process/calculate the route, but only collect the parameters, run a request to the ORS API and then renders the result.

It would be nice if you could create an issue on this repository: [https://github.com/GIScience/openrouteservice](https://github.com/GIScience/openrouteservice)

Then the team working on the back-end would be able to check this.

Kind regards,
Amon

**Comment by zorglubu** [comment]
OK thanks. And there are already different issues related to turn restrictions. Ex : [not adhering to turn restrictions without alternative routes](https://github.com/GIScience/openrouteservice/issues/807)
