### ISSUE TITLE
Add inspect data right click menu item

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/ors-map-client#116]
It would be beneficial for users to inspect the osm data directly with one click, instead of going to OSM website and do the query manually by copy pasting the lat long with the possibility to enter them in the wrong order.

On rightclick, of a menu entry like "inspect data" should open a new tab with the url:
`https://www.openstreetmap.org/query?lat=45.39297&lon=5.59126#map=17/45.39391/5.59226`
where the pattern is:
`https://www.openstreetmap.org/query?lat=y&lon=x#map=zoomlevel/y/x`

zoomlevel can be a static 18 as object queries are only available at high zoom levels and the user is often interested in only one or two features close to the point he clicked.

**Comment by amoncaldas** [comment]
This feature was implemented. 
I decided to build the link to OSM using the current zoom level of the map view, so that the user has more control over it. At lower zoom levels users can see data related to regions and countries, for example. At the same time, it is not expected that a user will be in a continent equivalent zoom level and try to inspect a street.
