### ISSUE TITLE
House number gets dropped on location selection

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#119]
When I search for _Schläuchenweg 6/3_, I get a suggestion for _Schläuchenweg, Heidelberg, Germany_ that drops the house number completely:

This is me typing _Schläuchenweg 6/3_
![Screenshot_2021-04-13 ORS Maps](https://user-images.githubusercontent.com/4692974/114546437-6d9f9a80-9c5d-11eb-829c-16d5f9eaa45f.png)

This is what happens after clicking the `Schläuchenweg, Heidelberg, Germany`-Button.
![Screenshot_2021-04-13 ORS Maps(1)](https://user-images.githubusercontent.com/4692974/114546470-785a2f80-9c5d-11eb-9f29-8bfc9b5193c0.png)

I'd expect 
I don't know if this is a problem with this specific street/house number or maybe with a `/` being part of the house number, since it works for addresses like _Bergheimer Straße 34_.

**Comment by amoncaldas** [comment]
I have reproduced this case. The problem is indeed happening, but the client itself is sending the request including the 6/3 and getting as response the two items that are shown in the picture you attached. The client is not stripping or filtering anything in this case. If you type "Schläuchenweg 6" only, you will see on the list "Schläuchenweg 6/3". So I suppose this is a problem with the API geocoder. The only possibility to solve this in the client might be to try to encode special characters, like slash, to be encoded. I will check this soon.

The request sent is:
https://api.openrouteservice.org/pgeocode/search?api_key=5b3ce3597851110001cf6248f91a3005b71645b88c266bf063bfbd62&text=Schl%C3%A4uchenweg%206/3&size=10&focus.point.lon=8.673791885375978&focus.point.lat=49.37432592004199&layers=country,region,macrocounty,borough,macroregion,county,neighbourhood,borough,street,address,coarse

**Comment by amoncaldas** [comment]
According to the tests I made using the API Playground, it seems that the [autocomplete endpoint](https://openrouteservice.org/dev/#/api-docs/geocode/autocomplete/get) can correctly deal with the and address containing a / , like "Schläuchenweg 6/3" and returns the address "Schläuchenweg 6/3" and the [geocoding search endpoint](https://openrouteservice.org/dev/#/api-docs/geocode/search/get) does not return the full address, dropping the house number.

Due to the differences between the results of geocoding search and geocoding autocomplete endpoints, and to the need of the keep the consistence between results displayed when the suggestion list is displayed and the app is in the search mode (listing "all" the results), the apps uses the search endpoint for the suggestion list (otherwise some results displayed on the list could not appear on the search mode). As the problem of dropping the house number seems to be on the geocoding search service, this issue will e closed. If new evidences are brought, the it can be reopen.
