### ISSUE TITLE
"Download Route"-popup doesn't close after route was downloaded

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#125]
This might just be my expectations colliding with intended behaviour, but when I click on the "Download"-Button in the "Download route"-popup, and have selected a place/app to open, I'd expect the "Download route"-popup to close once the download has started.

If it doesn't close, I'm unsure whether the download has actually started and is working.

**Comment by amoncaldas** [comment]
Hey @koebi 
Thanks for point this.
Well, from my very personal perspective, I do not expect the download modal to automatically close when the download is finished, because we offer different download formats and the user cold eventually want to download a second file in another format. 
When the content is ready to be download, the app shows a toaster saying "file ready" and the download starts (usually the browser will show a download progress).

Considering all these factors, I would not auto close the download modal. But of course if more people have the same expectation that you have, then we should change it. What do you think?

**Comment by TheGreatRefrigerator** [comment]
Hey @amoncaldas,
I think a user wanting the same route in 2 or more different formats is rather the exception.
One would usually need a polyline in either one or the other format for specific usecases.

I think auto close on saving a file should be the default.
I would even do the same for saving the app settings in the config view.

**Comment by amoncaldas** [comment]
Ok, thank you for the feedback from both of you. I change the behavior on both modals.

**Comment by shinkolobwe** [comment]
Hello, I have the same opinion:
"do not expect the download modal to automatically close when the download is finished, because we offer different download formats and the user cold eventually want to download a second file in another format."
I am nearly always downloading two formats for a route and never had any uncertainty whether the download was finished. 

So the current behavior, which also resembles the classic interface, is fine and useful.

**Comment by amoncaldas** [comment]
Closed via https://github.com/GIScience/ors-map-client/commit/1d562c6f294c1995cb93ec3f576fea5d4f1b660a
