### ISSUE TITLE
HU translation correction

### ISSUE THREAD

**Issue by debyos** [GIScience/ors-map-client#135]
Dear @amoncaldas or anyone who may be concerned,

I have spotted a minor mistake in the [right click label file](https://github.com/GIScience/ors-map-client/blob/f2879ccddf747555dd06735337332ad36c227651/src/fragments/map-view/components/map-right-click/i18n/map-right-click.i18n.hu-hu.js).

[A correction can be found here.](https://github.com/GIScience/ors-map-client/files/6407944/map-right-click.i18n.hu-hu.zip)

If you happen to have some time, you might update it.
Thanks

_Gábor_

**Comment by amoncaldas** [comment]
Hey @debyos 
The "error" you refer to is the change from "inspectDataOnOSM": "Adatok megtekintése az **OpenStreetMapen**" to "inspectDataOnOSM": "Adatok megtekintése az **OSM**"?
I had to make it shorter and use OSM instead of OpenStreetMapen because it was making the popup window to big and it is a problem in mobile devices. 
Can´t OSM be used as an acronym/abbreviation of OpenStreetMap in Hungarian?
Thanks

**Comment by debyos** [comment]
Hi @amoncaldas,

thanks for writing!
Hungarian is tricky. ;-) 
Words can have many forms and many endings (suffixes).

Then let's try so:
Adatok megtekintése az OSM-en

It is grammatically perfect and only 3 characters longer. Is it good so or should it be even shorter?

Cheers

Gábor

**Comment by amoncaldas** [comment]
Fixed via https://github.com/GIScience/ors-map-client/commit/7d45ab0deea54ae52e343814a1e9a289b2d627c6
