### ISSUE TITLE
Performance issue: adding intermediate waypoints

### ISSUE THREAD

**Issue by jayaddison** [GIScience/ors-map-client#139]
Hi folks - thanks for providing the updated responsive maps client for ORS.

This issue report is with regard to performance and usability while adding intermediate waypoints to an existing A-to-B route.

To reproduce the issue, compare route requests using the classic maps interface and the responsive maps interface, for a route from Berlin to Hamburg by bicycle:

- (classic) https://classic-maps.openrouteservice.org/directions?n1=53.044516&n2=11.708679&n3=8&a=52.52045,13.40732,53.576158,10.007046&b=1a&c=0&k1=en-US&k2=kma=52.52045,13.40732,53.576158,10.007046&b=0&c=0&k1=en-US&k2=km
- (responsive) https://maps.openrouteservice.org/#/directions/Berlin,Germany/Hamburg,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,1,152,3,160,5,128,6,1,217,8,9,128,26,1,88,110,41,243,72,96,110,125,206,60,170,216,6,200,196,131,74,3,240,48,1,194,14,136,8,0,29,83,192,136,155,14,80,243,160,64,6,111,0,13,186,92,224,2,121,131,212,128,57,128,90,104,232,44,5,115,220,154,12,144,155,211,111,75,113,24,67,121,110,64,2,218,7,162,34,195,162,194,184,1,121,66,6,227,226,72,2,250,37,0,0

With the route displayed, add an intermediate location; for example, Orianienburg, DE.

In the classic maps interface, the location autosuggestion interface accepts and responds to keypresses effectively, and the user experience remains fluid.

In the responsive maps interface, the page becomes slow and unresponsive when the user begins typing into the location field.

**Comment by amoncaldas** [comment]
Hey.
Thanks for pointing out this issue. It was just fixed via https://github.com/GIScience/ors-map-client/commit/c22d04a894533e93e1078e2bb55d868da49bd171 , https://github.com/GIScience/ors-map-client/commit/c22d04a894533e93e1078e2bb55d868da49bd171 and https://github.com/GIScience/ors-map-client/commit/41bca1c26307c752ee50507e2481e51049c6604b

**Comment by jayaddison** [comment]
Thank you @amoncaldas for the quick response and fix! - there are still one or two moments during which user input feels blocked, but it is _much_ better than it was previously.

Could I ask what the core of the fix was, out of interest?  (I see some potential typo fixes, perhaps relating to data format selection between client and server)

**Comment by amoncaldas** [comment]
Hey @jayaddison 

Instead of creating each input via hard code the ORS maps client uses a declaration strategy https://github.com/GIScience/ors-map-client/blob/develop/src/config-examples/ors-map-filters-example.js. With this approach the application is more flexible, allowing changing the filters easily. To make this work, a filters engine was created and this engine is responsible for rendering and keeping them updated, considering the filters relations and dependencies, reacting the to input changes. One of the files related to this engine is the https://github.com/GIScience/ors-map-client/blob/develop/src/support/dependency-service.js. 

Recently I made some changes in the `dependency-service.js` and it probably affected the way the filters are updated.  

There is a Model that is used to transfer data across components, called `MapViewData` https://github.com/GIScience/ors-map-client/blob/develop/src/models/map-view-data.js. Some components receive this `MapViewData` as parameter and watch for changes. This section of the readme explains a bit of the app flow: https://github.com/GIScience/ors-map-client#app-flow-overview.

The thing is that two components were watching the whole `MapViewData` object, when they should react only to changes in some specific properties. Because of this, each input change (keyup event) was triggering an update to several components. To fix this, the watch was set only to specific model properties and also the events are now treated with a debounce strategy https://stephencharlesweiss.com/javascript-debounce-throttle-function/.

**Comment by jayaddison** [comment]
Thank you @amoncaldas for the time to explain.

This might seem strange to mention, but in my experience performance differences like that are the kind of things that few users will ever take the time to report -- they're minor enough that most people will not realize that fixes/optimizations could be made by the authors -- and yet the compounding effect of that lost time (and additional frustration, even if it is subconscious) can have a large effect on the adoption of the software.

I'm probably repeating ideas you already understand and know, but just want to communicate them to make sure.  I hope to spend a bit more time here soon since ORS seems like an extremely valuable service; thank you for developing it.
