### ISSUE TITLE
Colour pallete of detailed view has poor usability

### ISSUE THREAD

**Issue by matkoniecz** [GIScience/ors-map-client#145]
Similar applies for stepness etc.

Why not use full colour scale for each detailed view?

![screen02](https://user-images.githubusercontent.com/899988/121351188-cae95c80-c92b-11eb-80d0-b1e5f8ce4b68.png)

Spot `surface=sand` here:

![screen03](https://user-images.githubusercontent.com/899988/121351249-d9377880-c92b-11eb-9112-3299416570fb.png)

**Comment by matkoniecz** [comment]
Purple for stepness is also bad, given red background.
![screen05](https://user-images.githubusercontent.com/899988/121352238-f02a9a80-c92c-11eb-814d-cd66b8e1839b.png)

**Comment by matkoniecz** [comment]
Not sure where it is defined - but I think that drastically different colors and using wide color range would be much better than the current display.

**Comment by matkoniecz** [comment]
BTW, is there some good way to export route view? So I can open it locally, without calling again routing service?

If i is achievable in some way and idea of revamping colors used in display is a good one, let me know - in such case I would definitely try to implement it.

**Comment by amoncaldas** [comment]
Hey @matkoniecz 
Thanks for the comments.

The colors can not be seen in isolation, but the whole range of colors used for several  extra information available must be analyzed together. The goal was to avoid using a color to represent multiple information/value, because it could create some confusion. So, a color pallet to represent the possible values of a given information was defined avoiding overlapping. Please take a look in the image attached (on the left, extra info - sidebar)
![colors](https://user-images.githubusercontent.com/13475791/121396062-490d2980-c953-11eb-8191-c89f03d7d9a2.png)


All the colors are defined here: https://github.com/GIScience/ors-map-client/blob/develop/src/resources/ors-dictionary.js#L98

If you have a suggestion that can harmonize the avoidance of color overlapping with a palette for each extra information and that at the same time output colors for each possible value that provide a better usability, please make a contribution. We will be happy to consider it.

**Comment by matkoniecz** [comment]
> was defined avoiding overlapping

I think that it was a mistake. Yes, it avoids user confusing surface map with steepness map - but at cost of making both steepness and surface maps basically unusable. (though maybe I am uniquely bad at recognizing shades of green/purple)?

**Comment by amoncaldas** [comment]
Do you have a concrete suggestion that consider the aspects I mentioned?

**Comment by amoncaldas** [comment]
Would you have a concrete suggestion that consider the aspects I mentioned?

**Comment by matkoniecz** [comment]
With constraint

> The goal was to avoid using a color to represent multiple information/value, because it could create some confusion. So, a color pallet to represent the possible values of a given information was defined avoiding overlapping

the improvements are possible, but minimal and I would not expect it to be sufficient to make detailed view usable.

I would encourage reconsidering this aspect of design.

Or testing is inability to spot given green shade among ones used to represent a different surface is just me.

Just grab one or two people - for example a friend/father/brother/daughter and ask them.

Closing as WONTFIX as going against deliberate taken design, but feel free to reopen.

**Comment by amoncaldas** [comment]
Thanks for your thoughts.
I understand your point and agree with it, but as said, there other points to be considered. We can not solve an issue and possibly create other(s) related to colors.
As I said, you are welcomed to suggest improvements. As mentioned, the colors are defined in a single file and organized by type of information. If you want to change specific colors, proposing new ones that offer a better contrast/usability and do not conflict with colors used to represent other information, please do it.
