### ISSUE TITLE
Feature request: Share URL with pre-filled routing destination but without a start (or other way round).

### ISSUE THREAD

**Issue by felixbecker2** [GIScience/ors-map-client#147]
I have a wish for a function for the webinterface at http://maps.openrouteservice.org/ to be able to share an URL to other people which has a routing destination or a routing start pre-filled, but not the other. (Use case: Share a map with a marker to an event venue where people can immediately also start to calculate their own route.)

The sharted URL should also include the set map area and zoom level and _optional_ pre-defined routing settings.

If there is already such a function, I am not able to find it, then please tell me (and maybe change usability of that feature).

*Many thanks for that otherwise very useful tool based on free data!*

Note: With the old UI http://classic-maps.openrouteservice.org/ this is possible, e.g. [classic-maps.openrouteservice.org/directions?n1=53.074787&n2=11.715916&n3=14&a=null,null,53.074794,11.715958&b=1a&c=1](https://classic-maps.openrouteservice.org/directions?n1=53.074787&n2=11.715916&n3=14&a=null,null,53.074794,11.715958&b=1a&c=1); the URL gets auto-generated in the browser's adress bar when selecting options.

**Comment by amoncaldas** [comment]
Hey @felixbecker2 
This was just implemented via dfc55b30c3770328d8744a942b5996de7f805e03

In order to be able to able to "see" the URL pattern (if you need it) you have to uncheck the option to compress URL after /data/ in the advanced section of advanced https://maps.openrouteservice.org/#/settings and then save it.

Now when a origin or destination is defined (via mouse click) or the user selects the directions mode and the destination is defined, the app synchronized the URL with this data. This also allows users to define filters/options for the route before defining origin and destinations and the changes in the filters are also synchronized with the URL, allowing the sharing of the current state of the view. Enjoy :-)
