### ISSUE TITLE
Geocoding seems broken?

### ISSUE THREAD

**Issue by koebi** [GIScience/ors-map-client#172]
When searching for `Jugendzentrum Fuchsfarm`, the client doesn't come up with anything, although the OSM has a place literally called `Jugendzentrum Fuchsfarm`:
![Screenshot 2021-10-05 at 10-49-56 Ors Maps](https://user-images.githubusercontent.com/4692974/135991676-bae47de7-8b54-49da-aee3-a7b1fd0817af.png)
This seems to change, however, if I move my map such that the place is included:
![Screenshot 2021-10-05 at 10-50-23 Ors Maps](https://user-images.githubusercontent.com/4692974/135991761-298a77d8-4b27-4454-8150-d31218a8088d.png)

Secondly, when I search for `Bergheimer Straße`, and Heidelberg is in my view, it gets found (although not as the first thing):
![Screenshot 2021-10-05 at 10-51-44 Ors Maps](https://user-images.githubusercontent.com/4692974/135991965-8b3919ee-c1f1-4a1e-8290-0a0a98ef32de.png)
If I want to specify that I mean the one in Heidelberg by continuing to type `hei`, it shows a bunch of places not even remotely related:
![Screenshot 2021-10-05 at 10-52-06 Ors Maps](https://user-images.githubusercontent.com/4692974/135992083-209bd39f-52b1-4ca7-934e-39ef917ba7bf.png)

**Comment by amoncaldas** [comment]
"However, in my opinion, if a result matches the input precisely (such as Jugendzentrum Fuchsfarm - it even highlights this), it should find it even outside of the bounds, and if its in bounds, it should put it first" 
-> the results returned by the geocode service are not reliable. In many cases, the best match does not represent the best/precise match or more then one is returned as best match. Additionally, the geocode service consider the browser language (automatically sent on the request) to return the results. So, for example, if your browser is in French and you search for "Germany", the results will bring "Allemagne" (Germany in French) instead of "Germany". So, the exactly match is not that simple.

The prioritize searching for nearby places-option is highly unintuitive and I didn't expect that. -> why?

We can/must continuously discuss/improve the search results, but it is important to be aware that it has already been discussed several times and it was realized that in many cases if we change the code to match one case that seems to be reasonable, many other cases not focused initially for that person are affected. So, we have to consider many use cases and balance how we perform in each one. 

The classic client is only able to show the places in the suggestion list, what in some cases might be a problem, since a place could be ranked in the 11 position and would not appear in the suggestion list and the users do not have the option to see "all results". The new maps client has this option, the search mode, and it shows the places on the map view. To get/show all the places, we use the geocode/search endpoint. Initially, we were using the `autocomplete` endpoint for the suggestions, but then it was noticed that the `autocomplete` endpoint returns different results when compared to geocode/search. So, one place could appear in the suggestion list and then not in the "show all" results view. So, the decision to use the geocode/search endpoint for both, suggestions and "show all" was made. 

This document gives an overview about how the place search criteria/strategy https://github.com/GIScience/ors-map-client/blob/develop/docs/search-results-criteria.md
