### ISSUE TITLE
sass dependecy

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/ors-map-client#274]
on linux ubuntu after `npm run dev`

```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)

```

**Comment by TheGreatRefrigerator** [comment]
Hi @stefanocudini, 
i guess you are running with one of the newer node versions?
the sass-loader is only [compatible with specific node versions](https://www.npmjs.com/package/node-sass).
Also due to some other dependencies i think currently only node 12 is supported (states that in the README.md) but i'm not sure right now.

Updating them is overdue anyway, but i currently can't find the time to do it. Afterwards hopefully we can support the newest LTS version of node.

For now you can try to downgrade to 12 or maybe 14 if it works (best use nvm or similar)

Best regards
