### ISSUE TITLE
Existing place or intermediate stops are lost after using “Directions to here”

### ISSUE THREAD

**Issue by joker234** [GIScience/ors-map-client#36]
Steps to reproduce:
1. Starting with a fresh instance of https://openrouteservice.org/map
2. Open the left sidebar
3. Type & find a place (e.g. Bismarckplatz Heidelberg)
4. Right-click on the map and select “Directions to here”
5. Existing Place is lost

Something similar:
1. Starting with a fresh instance of https://openrouteservice.org/map
2. Create any route with intermediate stops
3. Right-click on the map and select “Direct to here”
5. Intermediate Stops are lost

**Comment by amoncaldas** [comment]
Thanks for open, but I is intentional.
The app has some states: `place`, `directions`, `isochrones` and `roundtrip`. There are ways to switch from an state to another, like by clicking on the `directions` button, for example.
When first loaded, the app starts in the `place` mode. You can find a place and see its location and detailsor even share it. If desired, you can switch to the directions mode and use the already selected place as a target destination, by clicking on the `directions` button. But if you just find a place and don't change to directions, then when you start directions mode following another path, then the previously focused place will be discarded. You could also jump from a selected place to isochrones, for example, and the place would be also lost. 
I will close the issue for now. If any other aspect is added we may consider reopening it.

**Comment by joker234** [comment]
Just to be clear: You are saying it is intended that the intermediate stops are *lost*, when I just change the destination?

**Comment by amoncaldas** [comment]
Currently there is no "Directions to here" option in the right click menu when a route is calculated and displayed.
the options are:
Append as destination -> add the selected point to the end of the route (not stop is lost)
directions from here -> change the initial point of the route (no stop is lost)
Add stop here -> a stop is added (no stop is lost)
Direct to here -> calculate a route that goes **directly** to the selected point (as the name says, stops will be lostand the origin kept)
<img width="1439" alt="directions-to-here" src="https://user-images.githubusercontent.com/13475791/99281052-5e452e00-2832-11eb-8176-cf9b5d9375f0.png">
