### ISSUE TITLE
GeoJSON download: Downloads .json rather than .geojson

### ISSUE THREAD

**Issue by SColchester** [GIScience/ors-map-client#413]
GeoJSON download: Downloads .json rather than .geojson

When downloading the isochrone results and choosing GeoJSON, expect to download a file with extension .geojson, instead file downloads but has incorrect extension .json that needs to be manually fixed to ensure that it loads correctly in other services like QGIS, uMap, JOSM etc. 

![ORS-download](https://github.com/GIScience/ors-map-client/assets/43822967/53cdda91-f479-4d3b-bc68-7f8af2c8132d)

**Comment by TheGreatRefrigerator** [comment]
Hi @SColchester 

.json is a [totally valid](https://datatracker.ietf.org/doc/html/rfc7946) file ending for geojson files.

.geojson is often not matched to JSON files when viewing a file in an editor or other programs, which is why the .json is currently the default when downloading.

At least for QGIS i know that you can drag and drop a geojson-file.json in there without issues.
I don't know about umap and JOSM, but as .json is a valid geojson file ending i'd rather say they should support it.

**Comment by SColchester** [comment]
@TheGreatRefrigerator amazing, thanks for clarifying! I feel like I should have known this 😄 

uMap also has no problem with json files apparently! Seems like it is just a JOSM issue - will submit an issue to the team behind JOSM for that.
