### ISSUE TITLE
Bug in routing algorithms

### ISSUE THREAD

**Issue by Mi605** [GIScience/ors-map-client#429]
### Issue description:

Was on a cycle tour abroad and have got horribly wrong instructions from your service. Only one example:

**Wrong direction for bike:**
1 km extra detour, without any need. The short way is allowed for bicycles, but your algorithms won't route through it. Instead routing through heavy car traffic.
See [Wrong routing](https://i.imgur.com/ucBaiTV.png) (png screenshot)

**Additionally:** 
The waypoint 10 is wrongly named.
There is no hairstylist at spot 10 near the waterside. There is one somewhere in the neighborhood, but not at all near that waypoint.

**Extra details:**
These ways are free and allowed for bikes, and properly marked as such in OSM:
[Way segment 1 details at OSM](https://i.imgur.com/OPxhbLH.png) (png screenshot)
[Way segment 2 details at OSM](https://i.imgur.com/cEniYIC.png) (png screenshot)

**Proposed solution:**
Please fix your algorithms. Many thanks.

**Comment by koebi** [comment]
Hey,

the problem here is that there is no single _way_ where you draw the green line.
Instead, there is [this polygonal footway area](https://www.openstreetmap.org/relation/6405366), which is tagged as a relation (the tag is not on the way itself, but on the relation). 

We don't use relations for routing, and we don't have an open space routing implemented.

I'd recommend changing the underlying data - compare the same footway polygon next to your "10"-marker.
Here, crossing routes are mapped as single paths, which are then used for routing. The same can be done for the path crossing the mentioned area.

As for the mentioned naming of the waypoint, we are aware of the issues with our geocoder and are investigation options. However, as this will require a significant change in our infrastructure, it's not something that can be fixed quickly.
