### ISSUE TITLE
Suboptimal Handling of Road Access

### ISSUE THREAD

**Issue by McLP2** [GIScience/ors-map-client#463]
I don't know how much you can do about it, but I noticed some weird behavior when bike-routing from or to areas with private but bike-accessible paths and roads (e.g. at Hans-Dickmann-Kolleg, Karlsruhe).

![ors_restricted_area_example1](https://github.com/user-attachments/assets/b21911e9-1e30-4e99-b586-76f460bfc15a)
![ors_restricted_area_example2](https://github.com/user-attachments/assets/6684a1e9-ba8e-4623-9bf0-b5a2d0d8e409)
![ors_restricted_area_example3](https://github.com/user-attachments/assets/53cfaf94-7783-46ce-a903-367669fd9ac5)

I'd suggest to use more details from the osm tags and maybe allow otherwise forbidden roads if a waypoint is placed on them, potentially with a warning.

**Comment by TheGreatRefrigerator** [comment]
Hi @McLP2,

these are [issues with handeling access](https://github.com/GIScience/openrouteservice/issues/1398) of our openrouteservice backend and can't be fixed in the client.
`access=no` or `access=private` currently can't be used.
Best look at the existing ones before you open an other one there, but feel free to add info if you think it's missing
