### ISSUE TITLE
[openrouteservice] [Maps Website] Altitude window disappears on dragging route

### ISSUE THREAD

**Issue by JoergHW** [GIScience/ors-map-client#85]
Happens with firefox and chromium (both Linux).
How to reproduce:
Create a bicycle route with option 'bike'.
Open the altitude window (bottom left) to be visible on the map.
Move the path to create a waypoint --> altitude window is closed.

**Comment by amoncaldas** [comment]
It was designed with the idea that when a new route is calculated, the app state is reset to the `route ready` state, that, among other things:
- show the route info popup
- show the route ready toaster

I'm still thinking the pros and cons of keeping the altitude modal open when a route is changed. I will try to check if there are other side effects. Thanks for reporting.

**Comment by JoergHW** [comment]
My thinking is: If I change a route, I'd like to avoid/add some steepness. And then I want to see the resulting profile immediately. Maybe a good option is to add a check mark to make the window sticky - or use the two "pin" symbols known from other applications. If it's pinned, let it stay otherwise close it. This way the choice is to the user.

**Comment by amoncaldas** [comment]
The height graph itself is a separated component, also maintained by us, but used by other developers/applications. To have such feature we would have to add the stick/pin thing to the component and it might not be in the scope of the component itself. Thanks for the insights. I'm still evaluating the possibilities while doing other tasks :-)

**Comment by schmittlauch** [comment]
I'd like to second this request for not hiding the elevation profile at route changes.
I mostly use ORS for planning cycling tours, and mostly pin point a few main locations. The fine tuning of the route is then done via dragging it while reviewing the selected route.
The disappearance of the elevation chart is made worse because there is no single button to display it, but people have to scroll the left panel down quite a lot to find the – IMHO rather hidden – chart.
This is the most annoying change compared to the classic maps, apart of that you did a rather good job =)

**Comment by amoncaldas** [comment]
This was implemented. Now when a route changes, if the altitude graph was open, it will be kept open and refresh the data

**Comment by schmittlauch** [comment]
Thanks.
