### ISSUE TITLE
File import does not show any route

### ISSUE THREAD

**Issue by steventebrinke** [GIScience/ors-map-client#90]
Whenever I import a file, I receive the message: "Uploaded content rendered". However, nothing is shown. If I already had planned a route, it is cleared, but the uploaded route is not visible. I'm using Google Chrome.

I really love the import of the classic maps, which also allows showing a route on the map without destroying the already planned route. So I hope the import will become as powerful as that of the classic maps.

**Comment by amoncaldas** [comment]
Hey @steventebrinke 
Thanks for the feedback.
I have just calculated a route, exported it, reloaded the app and imported the file and it worked (rendered the route). 
Could you please give a concrete example that is not working?

The new maps client convert an valid import to a manipulable route, so that you can modify it the same way you would do with a non-imported route. As we don't have support for multiples routes at the same time then the existing route is cleared. You still has the option to use the classic client.
Thanks

**Comment by koebi** [comment]
Hey,

here's an [example](https://github.com/GIScience/ors-map-client/files/6083252/non-shown-example.zip) for a route that, as @steventebrinke described, gives the message "Uploaded content rendered", but doesn't actually show up on the map.

**Comment by amoncaldas** [comment]
Hopefully fixed via https://github.com/GIScience/ors-map-client/commit/84a9ee9a6213f2f3f1944ec90f70804b44958e4d
